ASP.NET PROJECT/FClubBarcelona/FClubBarcelona/Areas/Blog/Controllers/BlogController.cs
namespace FClubBarcelona.Areas.Blog.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using Attributes;
    using Models.BindingModels.Blog;
    using Service.Interfaces;

    [RouteArea("blog")]
    [RoutePrefix("blog")]
    [MyAuthorize(Roles = "Admin, BlogAuthor")]
    [HandleError]
    public class BlogController : Controller
    {
        private IBlogService service;

        public BlogController(IBlogService service)
        {
            this.service =  service;
        }
        [Route("AllArticles")]
        public ActionResult AllArticles()
        {
            IEnumerable<BlogArticleBm> model = service.GetAllArticles();
            return View(model.ToList());
        }

        [Route("AddArticle")]
        public ActionResult AddArticle()
        {
            return View();
        }



        [Route("AddArticle")]
        [HttpPost]
        public ActionResult AddArticle(BlogArticleBm model)
        {
            var user = User.Identity.Name;

            if (ModelState.IsValid)
            {
                service.AddArticle(model, user);
                RedirectToAction("AllArticles");
            }

            return this.View(model);
        }

      
        [HttpGet]
        [Route("Edit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogArticleBm blogArticleBm = service.EditArticle(id);
            if (blogArticleBm == null)
            {
                return HttpNotFound();
            }
            return View(blogArticleBm);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Edit")]
        public ActionResult Edit([Bind(Include = "Id,Title,Content,StartArticle,ImageTitle,YouTubeUrl")] BlogArticleBm blogArticleBm)
        {
            if (ModelState.IsValid)
            {
                service.Edit(blogArticleBm);           
                return RedirectToAction("AllArticles");
            }
            return View(blogArticleBm);
        }

        // GET: BlogArticleBms/Delete/5
        [Route("Delete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogArticleBm blogArticleBm = service.DeleteArticle(id);
            if (blogArticleBm == null)
            {
                return HttpNotFound();
            }
            return View(blogArticleBm);
        }

        // POST: BlogArticleBms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {

            service.Delete(id);
            return RedirectToAction("AllArticles");
        }

        [Route("Home")]
        public ActionResult Home()
        {
            return View();
        }
      
        


    }
}

ASP.NET PROJECT/FClubBarcelona/FClubBarcelona/Areas/Blog/Views/Shared/_BlogLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>FcBarcelona-Blog</title>
    <link href="https://media-static.fcbarcelona.com/fcb_theme/images/favicon.ico" rel="Shortcut Icon">
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>              
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home",new {Area = ""},null)</li>   
                <li>@Html.ActionLink("Articles", "AllArticles", "Blog", new { Area = "Blog" }, null)</li>  
                @if (User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("Admin", "Home", "Admin", new {Area = "Admin"},null)</li>
                }
                  
            </ul>
            @Html.Partial("_BlogLoginPartial")
        </div>
    </div>
</div>
  
<style>
    .navbar {
        background-color: #39870C;
      
    }
</style>
<div class="container body-content">
    
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ASP.NET PROJECT/FClubBarcelona/FClubBarcelona/Areas/Blog/Views/Shared/_BlogLoginPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", new { Area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
    @Html.AntiForgeryToken()

    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Manage", "Account", new { Area = "" },null)
        </li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
    }
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Log in", "Login", "Account", new { id = "loginLink", Area = "" },null)</li>
    </ul>
}